apiVersion: v1
kind: Pod
metadata:
  name: hello-world
  labels:
    run: test
spec:
  containers:
  - image: docker.io/lorenzam99/hello-world:latest
    name: test
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
