apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  steps:
  - name: build-and-push
    image: quay.io/buildah/stable
    workingDir: /workspace/output
    env:
    - name: IMAGE
      valueFrom:
        configMapKeyRef:
          name: config
          key: dockerhub-image
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: cred-secret
          key: username-dockerhub
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: cred-secret
          key: pat-dockerhub
    script: |
      #!/bin/sh
      cd HelloWorld
      buildah --storage-driver=vfs bud -t $IMAGE .
      echo 'Checking if image is built:'
      buildah images helloworld:latest
      buildah login -u $USERNAME -p $PASSWORD docker.io
      echo "Pushing image to Docker Hub"
      buildah --storage-driver=vfs push $IMAGE
  workspaces:
  - name: output
