apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  steps:
  - name: buildah-build
    image: quay.io/buildah/stable
    workingDir: /workspace/output
    env:
    - name: DOCKERHUB_URL
      valueFrom:
        configMapKeyRef:
          name: config
          key: dockerhub-url
    script: |
      #!/bin/sh
      cd HelloWorld
      buildah bud -t $DOCKERHUB_URL .
  - name: buildah-push
    image: quay.io/buildah/stable
    workingDir: /workspace/output
    env:
    - name: DOCKERHUB_URL
      valueFrom:
        configMapKeyRef:
          name: config
          key: dockerhub-url
    securityContext:
      privileged: true
    script: |
      #!/bin/sh
      echo "Pushing image to Docker Hub"
      buildah push $DOCKERHUB_URL
  workspaces:
  - name: output
