apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: clone-build-push-exec
spec:
  tasks:
  - name: clone
    taskRef:
      name: git-clone
    workspaces:
      - name: output
        workspace: output
  - name: build-and-push
    runAfter:
      - clone
    taskRef:
      name: build-and-push
    workspaces:
      - name: output
        workspace: output
  - name: execute
    runAfter:
      - build-and-push
    taskRef:
      name: execute
    workspaces:
      - name: output
        workspace: output
  workspaces:
    - name: output  