apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
    name:   git-clone
spec:
    steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning up workspace: $(workspaces.output.path)"
        rm -rf $(workspaces.output.path)/*
        cd workspace/output
        ls -l
        echo "Workspace cleaned"
    - name: clone
      image: alpine/git
      workingDir: /workspace/output
      env:                
      - name: GITHUB_USER         #Iniettiamo i valori contenuti nel secret come variabili d'ambiente
        valueFrom:
          secretKeyRef:
            name: git-secret
            key: username
      - name: GITHUB_TOKEN
        valueFrom:
          secretKeyRef:
            name: git-secret
            key: pat
      - name: REPO_URL            #Iniettiamo i valori contenuti nella configMap come variabili d'ambiente
        valueFrom:
          configMapKeyRef:
            name: config
            key: repo-url
      - name: BRANCH
        valueFrom:
          configMapKeyRef:
            name: config
            key: branch
      script: |
        #!/bin/sh
       
        echo "Cloning repository into: $(workspaces.output.path)"
        URL=$(echo -n $REPO_URL | sed 's|^https://||')
        git clone -b $BRANCH "https://$GITHUB_USER:$GITHUB_TOKEN@$URL"  
    - name: check
      image: alpine
      workingDir: /workspace/output
      script: |
        #!/bin/sh
        ls -l
        cd HelloWorld
        ls -l
        cd src
        ls -l
        echo "Repository cloned successfully"
    workspaces:
    - name: output
        