apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
    name: compile
spec:
    steps:
    - name: compile
      image: openjdk:17-jdk-slim
      workingDir: /workspace/output
      script: |       #compila il codice sorgente con javac
        #!/bin/sh
        cd HelloWorld
        javac -d . ./src/HelloWorldMain.java
        echo "checking if .class is under $(workspaces.output.path)/HelloWorld"
        ls -l
    workspaces:
    - name: output
