apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: pipelinerun-helloworld
spec:
  pipelineRef:
    name: pipeline-helloworld
  workspaces:
  - name: output
    persistentVolumeClaim:
      claimName: my-pvc