apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: pipeline-helloworld
spec:
  tasks:
  - name: clone
    taskRef:
      name: git-clone
    workspaces:
      - name: output
        workspace: output
  - name: compile
    runAfter:
      - clone
    taskRef:
      name: compile
    workspaces:
      - name: output
        workspace: output
  - name: build-and-push
    runAfter:
      - compile
    taskRef:
      name: build-and-push
    workspaces:
      - name: output
        workspace: output
  - name: deploy
    runAfter:
      - build-and-push
    taskRef:
      name: deploy
    workspaces:
      - name: output
        workspace: output
  workspaces:
    - name: output  