apiVersion: v1
kind: Secret
metadata:
  name: cred-secret
type: Opaque
data:
  username-github: TG9yZW56b0Ft
  pat-github: Z2hwX3V3bGtDajMzNk9jVUo2dnBYdXhSa1JMeGJwV0pNNzEzc2lSdg==
  username-dockerhub: bG9yZW56b2Ftb3JldHRpOTlAZ21haWwuY29t
  password-dockerhub: X1VrYXNzXzk5